#!/bin/bash

# apt install xvfb gnome-shell x11vnc 

# Make sure to run:
# x11vnc -storepasswd ~/.vnc/passwd
# before running this script

# "Monitor" dimensions
width=1920
height=1080
# every time
source $HOME/.bashrc
Xvfb $DISPLAY -screen 0 ${width}x${height}x16 &
gnome-shell --replace &
x11vnc -display $DISPLAY -forever -loop -noxdamage -repeat -rfbauth $HOME/.vnc/passwd -rfbport 5900 -shared &

