#!/bin/bash
[ "$(id -u)" != 0 ] && echo "Rerun $0 as root"; exit

# Make sure the packages are installed (even with the -y flag it may still require user input, because apt is dumb like that)
echo "Installing dependencies..."
apt install xvfb gnome-shell x11vnc -y

# Set VNC password
printf "\n\nWhat should the VNC password be?\n"
read -r PASSWD
x11vnc -storepasswd $PASSWD ~/.vnc/passwd

# Setup service
service="/etc/systemd/system/vnc.service"
curl https://raw.githubusercontent.com/East-Helena-Public-Schools-IT/scripts/main/linux/vnc/vnc.service > $service
chmod 664 $service

# Download vnc script
wget -P /usr/local/bin/ https://raw.githubusercontent.com/East-Helena-Public-Schools-IT/scripts/main/linux/vnc/headless-vnc
chmod +x /usr/local/bin/headless-vnc

# Eanble service
systemctl daemon-reload
systemctl enable vnc
systemctl start vnc