#!/bin/bash

# Setup service
service="/etc/systemd/system/vnc.service"
curl https://raw.githubusercontent.com/East-Helena-Public-Schools-IT/scripts/main/linux/vnc/vnc.service > $service
chmod 664 $service

# Download vnc script
wget -P /usr/local/bin/ https://raw.githubusercontent.com/East-Helena-Public-Schools-IT/scripts/main/linux/vnc/headless-vnc

# Eanble service
systemctl daemon-reload
systemctl enable vnc
systemctl start vnc